### PR TITLE
Broaden meaning of Specification to include how to do things.

### PR DESCRIPTION
**Pull request by uscholdm**
Addressing issue #405

### CODE REVIEW

**Review by mkumba — COMMENTED** [review]
Admittedly the word specification is ambiguous in English in this regard, but what are we gaining by also becoming ambiguous.  I think the issue is as it was if something was a specification we would know what it was, now we're not going to be sure if it is evaluative, or generative. 

There are behaviors that we can imagine implementing on instances of these classes.  If the instance is template, then saying something like "new()" should create something.  If something is a specification saying something like "conformsTo" we should get a boolean.  But if we mix them all together we won't know which ones conform to which behaviors.

**Comment by uscholdm** [comment]
> @mkumba  Admittedly the word specification is ambiguous in English in this regard, but what are we gaining by also becoming ambiguous. I think the issue is as it was if something was a specification we would know what it was, now we're not going to be sure if it is evaluative, or generative.

So maybe that's a good reason to have two major subclasses, which could be called EvaluativeSpecificaton and GenerativeSpecification (or maybe HowToSpecification).  We decided to not do that till there was a good reason to.  There are some things that I model as Specification that I would not make subclasses of either, so I'd not want them to be a disjoint union. For example, in Platts there is a class called TimeOfDayInTimeZone which means 'the time of day on a 24 hour clock in a given time zone, ignoring daylight savings time.' It is informational, part of the description of an assessment, when it takes place. Having a disjoint union would nudge one into thinking one had to choose. I would not want to be forced to think about whether TimeOfDayInTimeZone or SpecEntry or various other things necessarily go into one place or the other.  Unhelpful.

**Review by rjyounes — COMMENTED** [review]
Michael, I think this PR should be closed in order to consider Dave's comments on the issue. I think they have merit.

**Comment by uscholdm** [comment]
@rjyounes They do have merit, and any extended discussions ought take place back at the issue. However, if we can reach quick agreement, we can probably stay here on the PR.

**Comment by marksem** [comment]
I concur with the merit of Dave's concerns.  I'm sorry to have missed the issue review yesterday where the DECISION was made.  Because I still think  a Specification is a "what" but not a "how" (process) for the reasons Dave brings up. Furthermore, Specification is sub of Requirement.  That again makes me think it is a "what" but not a "how".  I think processes fit under Task Template. I thought that's what Task Template was pretty much about. 

As for "EvaluativeSpecificaton and GenerativeSpecification", my initial reaction is to strongly object.  These are starting to sound like BFO classes, i.e., not natural, common concepts, and I think that would start to undermine Gist's appeal.

**Comment by uscholdm** [comment]
CLOSING due to lack of consensus. Discussion continuing at issue #405

**Comment by rjyounes** [comment]
@marksem Totally agree about EvaluativeSpecification and GenerativeSpecification. Frankly, I can barely understand what they mean unless I think harder than I should have to.

**Pull request closed without merging**
