### PR TITLE
Deprecate gist:Room. 

### LINKED ISSUE #102: Problems with gist:Room
The term specification does not define a "room" in the ordinary sense: e.g., elevators, staircases, hallways, and closets are direct parts of buildings but not rooms in the ordinary sense; and they can all have IDs. Also, a room in the ordinary sense can be a direct part of a wing, where the wing is a direct part of a building. In this case the room is a part of the building but not a direct part. According to the gist definition of Room, the wing is a Room and the room within a wing is not a Room. We could rename the class, but the usefulness of a class that includes elevators, staircases, hallways, wings, and some rooms but not others, is dubious; this is confirmed by the difficulty of finding an accurate name for the class - i.e., it's not a real concept. I suggest modifying the definition of gist:Room to be a semantically and coherent reflection of the concept of "room."

### PR DESCRIPTION
**Pull request by rjyounes**
Fixes #102 

Note that gist:Room also had to be removed from three union classes (which are actually one union class repeated three times; see #334)

### CODE REVIEW

**Comment by sa-bpelakh** [comment]
In order to keep this a minor change, deprecate the class _only_, leaving it in the other axioms. When we move to the next major release, deprecated classes will be removed entirely, and the axioms will be trimmed at that time.

**Comment by rjyounes** [comment]
@sa-bpelakh IMO non-deprecated terms should not reference deprecated terms. Note that gistCore correctly does _not_ import gistDeprecated, while gistDeprecated correctly does import gistCore. Therefore, if one imports only gistCore, the axioms are rendered meaningless anyway. 

I would prefer to withdraw this change until the next major release.

**Comment by rjyounes** [comment]
We can add a skos:editorialNote or rdfs:comment to ourselves to record this intention.

**Comment by rjyounes** [comment]
Closing the PR; will make the change when we are ready for the next major release.

**Comment by rjyounes** [comment]
Deferring issue till next major release.

**Pull request closed without merging**
