### PR TITLE
Add owl:Thing assertions to duration units. Fixes #775.

### LINKED ISSUE #775: 3 terms missing `rdfs:isDefinedBy` triples
I'm writing some basic Best Practice-checking code, and in the process I noticed that there are just 3 terms (from the 289 terms in gist) that are missing `rdfs:isDefinedBy` triples, namely:
- `gist:_day`
- `gist:_millisecond`
- `gist:_minute`

I assume this is just a minor oversight (as the other 14 `owl:NamedIndividual` instances do include that triple). And it's easy to fix up by just adding the missing triples.

### PR DESCRIPTION
**Pull request by dylan-sa**
Fixes #775.

### CODE REVIEW

**Review by rjyounes — COMMENTED** [review]
I'm not convinced this is the right solution. We shouldn't have to add `owl:Thing` assertions to our named individuals; a better approach is to modify onto_tool: see [issue #105](https://github.com/semanticarts/ontology-toolkit/issues/105). 

@uscholdm  What do you think?

**Comment by rjyounes** [comment]
The other option is just to change the yaml file to use `all` rather than `strict`. Is there any reason not to do this?

**Comment by dylan-sa** [comment]
I offer this as a quick fix, but that is a fair point about using `all` rather than `strict`. I agree that using `all` would be the better option in the long term, assuming all of the `NamedIndividual` and `Thing` assertions are removed.

**Comment by rjyounes** [comment]
I don't think we need a quick fix, so I'm closing this.

**Pull request closed without merging**
