### PR TITLE
Issue292 Demodularize gist

### PR DESCRIPTION
**Pull request by marksem**

### CODE REVIEW

**Comment by marksem** [comment]
@sa-bpelakh , I don't think it invalidates module imports.  I think if someone imports an un-versioned module other than gistCore,, e.g. gistAddress, that they'll get 9.2.0, and its imports closure (all 9.2.0).  Which *is* (and ever will be) the most recent version of gistAddress (and its imported modules).  Of course, this is why I think it is better to import a specific version of an ontology (use versionIRI), so you know exactly what concepts you are committing to.

**Comment by rjyounes** [comment]
@marksem I agree that imports should always use versioned IRIs; it doesn't make sense to import something when you don't know what you're getting. But (to state the obvious) what makes sense is not necessarily what happens in practice.

If someone imports unversioned gistCore and (redundantly) unversioned gistAddress, there is the potential for unresolvable clashes, since they'll get version 9.3.0 (or whatever) of gistCore, and 9.2.0 of gistAddress, and there may be conflicts between term definitions in the two versions. (See https://www.w3.org/2007/OWL/wiki/Imports#Clashing_versions). Note that you could say the same thing if they import, say, gistCore9.2.0 and gistAddress9.1.0, but this is specifically prohibited by the [OWL spec](https://www.w3.org/TR/owl2-syntax/#Imports): "The import closure of O should not contain ontologies O1 and O2 such that O1 and O2 are different ontology versions from the same ontology series."

**Comment by marksem** [comment]
Wonder if this would be a good time to switch to Turtle format. :)

**Comment by rjyounes** [comment]
@marksem Sorry, when you said "maybe now's the time" I thought you meant this release, not this PR. There is a separate issue #223 for this, which hasn't been decided on, and in any case I don't think this change should be included in this PR in order to keep things atomic. What do you think?

**Comment by rjyounes** [comment]
We've determined this will be a minor rather than major change, based on the fact that we encourage users to import versioned rather than unversioned IRIs.

**Comment by uscholdm** [comment]
@rjyounes said: 
> There is a separate issue #223 for [Turtle], which hasn't been decided on, and in any case I don't think this change should be included in this PR in order to keep things atomic. What do you think?

I agree. Good practice.

**Comment by marksem** [comment]
Fixes #292

**Pull request merged**
