### PR TITLE
Release/11.0.0

### PR DESCRIPTION
**Pull request by dylan-sa**
Changes in preparation for creation of release package:

- Minor adjustments to release notes to ensure all v11 changes are included
- Migration scripts: Added some missing properties/classes; added 'range change' scripts

### CODE REVIEW

**Review by Jamie-SA — CHANGES_REQUESTED** [review]
Need to add new queries to migration scripts.

**Review by rjyounes — APPROVED** [review]

**Comment by rjyounes** [comment]
@Jamie-SA Have you reviewed Dylan's changes?

**Comment by dylan-sa** [comment]
@Jamie-SA Good catch. I believe it's fixed now with my latest commit.

**Comment by rjyounes** [comment]
I'm going to leave the merge till Monday when we're sure the release package is good.

**Pull request merged**
