### PR TITLE
Revise local names according to adopted conventions. Fixes #188

### LINKED ISSUE #188: Define and implement conventions for local names
This is a spin-off of #20, which we decided to limit to labels. Conventions articulated there for composing local names are repeated below. The gist Style Guide (forthcoming) also records these conventions, but only as proposals since there remains significant controversy.

```
Classes: camelcase, initial uppercase. Acronyms also camel-cased so that word boundaries are unambiguous - e.g., AmaGuideline not AMAGuideline, UriScheme not URIScheme. Alphanumeric characters only - e.g., Isbn10, not Isbn-10 or ISBN-10. ID is an exception: Merriam-Webster accepts this as a word in all-caps.

Properties: camelcase, initial lowercase, acronyms as above.

Both: non-standard abbreviations should not be used: e.g., hasUoM should be hasUnitOfMeaure.
```

### PR DESCRIPTION
**Pull request by rjyounes**

### CODE REVIEW

**Comment by rjyounes** [comment]
In the interests of getting this done and the `10.0.0` release out the door, I suggest that reviewers flag only errors, and changes they cannot live with. I have kept the changes conservative to minimize disagreement, even in cases where I felt a fuller rewording would be an improvement. We will have the opportunity to make changes in future major releases. In particular, we will likely release a revamp of times, in which case all or many of the predicates will change and names can be re-evaluated then. In addition, we will probably be removing a lot of inverses (#506). 

I added 'biological' to the parent/offspring predicates to align with the definitions, but there is an issue about whether this limitation is appropriate (#444). I also reversed the order to hasX vs isXOf.

**Comment by rjyounes** [comment]
@daliadahleh, because @uscholdm is off for a while, I'm requesting a review from you. As I mentioned to the other reviewers, unless you find something egregious or that you can't live with, or have a minor comment that can be easily fixed, let's try to pass this one through. It's holding up the release and we have been working on this for 18 months! Thanks!

**Review by marksem — CHANGES_REQUESTED** [review]
Shouldn't `offsetToUniversal` have been changed to something like `hasOffsetToUniversal` ?

`precedesDirectly' appears to be missing annotations. This is because it is not declared anywhere, but only referenced as the inverse of `followsDirectly`.

Why is `latitude` an object property as well as a data property when I view in protege? Ah, b/c its range is xsd:double, and all the datatypes are classes now, at least according to Protege.  Same issue for longitude, sequence, baseConversionFactor, and more.

**Comment by rjyounes** [comment]
I just noticed that all the datatypes are classes in Protege. That's an error we need to track down. They're also shown as datatypes. It's possibly a Protege bug. Do you have time to look into that, since you know Protege better than I do?

You're right about `offsetToUniversal`. And I'll check on `precedesDirectly`. Good catches!

**Comment by rjyounes** [comment]
Changed target branch from `develop` to `release-`10.0.0`.  This PR was created before the latter was split off from the former; it now needs to be merged into the release branch, and will be merged to `develop` along with all other commits on the release branch.

**Comment by marksem** [comment]
@rjyounes , yes I can investigate to see if Protege is doing something wrong, or if it is a logical entailment somehow.

**Comment by rjyounes** [comment]
Fixed `offsetToUniversal` and restored `precedesDirectly`.

**Comment by rjyounes** [comment]
@marksem The ontology changes we discussed are ready for re-review. Then we're awaiting your investigation of the Protege issue.

**Comment by rjyounes** [comment]
@marksem @sa-bpelakh  I now recall that I've seen this problem before, and it's a protege bug.  The relevant OWL is:
```
gist:numericValue
	a owl:DatatypeProperty ;
	rdfs:domain gist:Magnitude ;
	rdfs:range [
		owl:unionOf (
			owl:rational
			owl:real
			xsd:byte
			xsd:decimal
			xsd:double
			xsd:float
			xsd:int
			xsd:integer
			xsd:long
			xsd:negativeInteger
			xsd:nonNegativeInteger
			xsd:nonPositiveInteger
			xsd:positiveInteger
			xsd:short
			xsd:unsignedByte
			xsd:unsignedInt
			xsd:unsignedLong
			xsd:unsignedShort
		) ;
	] ;
        .
```
This is valid OWL because the range of owl:unionOf is rdf:List. Protege doesn't handle it properly. I've checked out TBC and it has no problem with it. This is very unfortunate because many of our users will view the ontology in Protege. Thoughts? @sa-bpelakh We could add a note to the property, at least.

**Comment by sa-bpelakh** [comment]
> @marksem @sa-bpelakh I now recall that I've seen this problem before, and it's a protege bug. The relevant OWL is:
> 
> ```

Should we remove `rdfs:range` and replace it w/ `gist:rangeIncludes`, so we document it but not confuse Protege? How important is this correction?

**Comment by marksem** [comment]
Apparently Protege is ok with something like this:
`<http://ns/myprop1> rdf:type owl:DatatypeProperty ;
                    rdfs:range [ rdf:type rdfs:Datatype ;
                                 owl:unionOf ( owl:rational
                                               owl:real
                                             )
                               ] .

`

So maybe we're just missing the `rdf:type rdfs:Datatype` part and then we're all good.  Did not get time to fully test yet.

**Comment by rjyounes** [comment]
@marksem I've moved the Protege issue over to #552. I assigned it to myself, but feel free to reassign it to yourself if you have a chance to test it.

**Comment by rjyounes** [comment]
The release note might be a bit confusing: I included a note about updates to the gist style guide, although those are not in this PR, in order to avoid one merge conflict.

**Review by marksem — APPROVED** [review]

**Pull request merged**
