### PR TITLE
Fix serializer pre-commit permissions problem

### LINKED ISSUE #1006: Fix pre-commit permissions problem
Perhaps a Mac-only problem: Serializer pre-commit hook keeps changing permissions, which git considers a change and wants to commit. This happens repeatedly and is a real nuisance. The solution is to copy the serializer pre-commit to the hooks directory and invoke that one from the main pre-commit; the one in the repo is then not being executed.

### PR DESCRIPTION
**Pull request by rjyounes**
Fixes #1006

### CODE REVIEW

**Review by Jamie-SA — APPROVED** [review]
I am not real thrilled with this change. This means that the hook will not automatically be updated when changed in the git repo.

However, there is already issue #891 about having to deal with this for the main hook, so it could be dealt with in the same way.

**Comment by rjyounes** [comment]
> This means that the hook will not automatically be updated when changed in the git repo.

If the main pre-commit changes in the repo you have to rerun `/tools/setup.cmd`. This handles changes to the serializer pre-commit the same way, unless I'm missing something.

**Comment by Jamie-SA** [comment]
Yes, but see the issue I referenced: #891 
You don't currently have to run setup.cmd if the serialize/pre-commit changes, but you will after this change.

**Comment by rjyounes** [comment]
I see. I see you added a comment to that effect on #891. It seems to me to be in principle the same issue.

**Pull request merged**
