### PR TITLE
Add serializer instructions to README

### PR DESCRIPTION
**Pull request by marksem**

### CODE REVIEW

**Comment by mkumba** [comment]
So what do I do with this?


  1.  Am I supposed to add the serializer instructions, or did you add them an want me to review them?
  2.  Ok I think I see if I expand the thing, you have written the instructions.
  3.  Do I merge the pull request or is there someway I say “ok by me”
  4.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by uscholdm** [comment]
To Dave:
Mark added instructions, and invited you to review them.
See what others say in their review and when ready to merge you can do so.   I'm no expert on this, but I think if you click on the green button saying to review, it gives options, one is "Approve". IF you select that I think it does the merge.  Boris or MarkW are better able to explain this.

**Comment by mkumba** [comment]
Clicked the green button, didn’t see any approve or comment options, seems like it just took it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by uscholdm** [comment]
More than one way to skin a cat…

**Comment by marksem** [comment]
There are buttons both to approve buttons and to do the merge.  When you get a notification like this, the idea is to **comment** on it and/or **approve** of the changes.  You can also OPTIONALLY click some button/link to **do the merge**.  You both commented.  I think Michael approved.   And Dave, you obviously succumbed to the greenness of a button and clicked it, and thus approved it.  :) Since you've already done it, IDK what the button says, but it may say "Merge" or "Accept".  

I can tell you did by this message in the log of actions above:

`mkumba merged commit 008a7d4 into master 20 hours ago`

**Pull request merged**
