### PR TITLE
Add MonetaryPerDuration and CurrencyPerDurationUnit classes. Fixes #846

### LINKED ISSUE #846: Add magnitude and unit classes for monetary-per-duration
gistAcct, gistHR, and gistProfSrv all require the classes `MonetaryPerDuration` (subclass of `Magnitude`) and `CurrencyPerDurationUnit` (subclass of `UnitOfMeasure`). Since gistAcct and gistHR are independent - neither imports the other - these classes need to be promoted to gistCore. They are needed now rather than waiting for the post-12.0.0 release.

Specific units, such as USD_per_hour or US_per_year can be defined in client ontologies rather than gistCore.

### PR DESCRIPTION
**Pull request by rjyounes**
Fixes #846. 

Due to some technical issues regarding branch names, I had to recreate the former PR #847. You can refer to comments there.

### CODE REVIEW

**Comment by dylan-sa** [comment]
Continuing the discussion from #847:
> Are these definitions correct in that they follow current practice in defining magnitude and unit classes? This is what needs to be reviewed. 

Yes, makes sense to keep that as the focus for now. I think the relevant analogs would be subclasses of `ProductUnit` and `RatioUnit`, because `CurrencyPerDurationUnit` falls under the latter and product units are structurally similar w/ multipliers and multiplicands rather than numerators and denominators. Here's what we have currently:

- `VolumeUnit` and `AreaUnit` use qualified cardinality restrictions. (Not quite the pattern I suggested in 847, but close.)

- `CoherentProductUnit` and `CoherentRatioUnit` use `allValuesFrom`. (Part of what I suggested with 847 but w/o the cardinality restrictions.)

To more closely align with current practice, we might go w/ one of these patterns.

**Comment by rjyounes** [comment]
@dylan-sa OK, the samples I looked at must have been only the ones with someValuesFrom. Here's what I propose:

* For this issue, change someValuesFrom to allValuesFrom
* hasNumerator and hasDenominator are functional properties. That will achieve the cardinality constraint you propose, but it's more generally applicable than here so I wouldn't want to add it here. Same for hasMultiplier and hasMultiplicand. Add an issue for this. 
* The qualified cardinality and someValuesFrom cases seem to me just wrong. Add an issue to use allValuesFrom instead. (However, this is going to be subsumed by the units and magnitudes group, so we may not want to actually implement this.

Will this satisfy all of your concerns?

**Comment by dylan-sa** [comment]
Sounds good to me. 👍

**Comment by rjyounes** [comment]
@dylan-sa Change made. Please give a quick review.

**Comment by rjyounes** [comment]
Issues added: #857 (functional properties) and #858 (allValuesFrom).

**Pull request merged**
