### PR TITLE
Change prefix xs to xsd and add to release notes. Fixes #158.

### LINKED ISSUE #158: Change prefix xs to xsd throughout
See discussion on PR #156. 

xsd is the standard.

### PR DESCRIPTION
**Pull request by pwin**

### CODE REVIEW

**Comment by rjyounes** [comment]
I'm going to amend my previous comment about content of release notes: we should use the short description rather than a link to the issue. People will be downloading this from the web and will want documentation of changes without having to refer to the repository.

**Comment by Jamie-SA** [comment]
Am I correct in remembering that on the phone call it was decided to have both a short comment and a link to any issues for more complete information?

**Comment by rjyounes** [comment]
@Jamie-SA That is correct.

**Comment by pwin** [comment]
Sorted

**Pull request merged**
